test: cover File-based catalog image
securesign/structural-tests pull request #11
Opened 2024-09-26 15:05 UTC by osmman

2024-09-26 16:06 UTC, petrpinkas requested changes

2024-09-26 16:06 UTC, petrpinkas commented on test/acceptance/fbc_images_test.go
> +const olmPackage = "rhtas-operator"
I'd move those to other constants

2024-09-27 09:23 UTC, osmman commented on test/acceptance/fbc_images_test.go
> +				expectedChannels := []string{"stable", "stable-v1.1", "stable-v1.0"}
Right now I do not know source of data which we can use for CI. So I take simplest solution hard code it 😄.

2024-09-27 10:46 UTC, petrpinkas approved these changes

2024-09-27 10:56 UTC, merged